---
- name: Atualizacao do Servidor
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Esperar SSH ficar disponível
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Executar apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_result
      until: apt_result is success
      retries: 10
      delay: 10
    
- name: Instalação do Nginx
  hosts: all
  become: yes
  tasks:
    - name: Instalar o Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Iniciar e habilitar o serviço Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Criar pagina HTML customizada
      copy:
        content: "<h1>Deploy Automatizado com Terraform e Ansible</h1>"
        dest: /var/www/html/index.html