---
- name: Atualizacao do Servidor
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Esperar SSH ficar dispon√≠vel
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Executar apt upgrade
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_result
      until: apt_result is success
      retries: 10
      delay: 10